schema:
  - ${HASURA_GRAPHQL_URL}/v1/graphql:
      headers:
        x-hasura-admin-secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
documents:
  - "app/**/*.{graphql,ts,tsx}"
  - "!app/_gql/**/*.{graphql,ts,tsx}"
ignoreNoDocuments: true
generates:
  ./app/_gql/:
    preset: client
    presetConfig:
      fragmentMasking: false
    config:
      dedupeFragments: true
      useTypeImports: true
      skipTypename: true
      enumsAsTypes: true
      scalars:
        bigint: number
        uuid: string
        date: string
        time: string
        daterange: string
        timestamptz: string
extensions:
  languageService:
    cacheSchemaFileForLookup: true
